services:
  # Frontend - Angular
  frontend:
    build: ./frontend
    container_name: elibrary-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - elibrary-network

  # Backend - Laravel
  backend:
    build: ./backend
    container_name: elibrary-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=elibrary
      - DB_USERNAME=root
      - DB_PASSWORD=secretpassword
    depends_on:
      - mysql
    networks:
      - elibrary-network

  # Base de donn√©es - MySQL
  mysql:
    image: mysql:8.0
    container_name: elibrary-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: elibrary
      MYSQL_ROOT_PASSWORD: secretpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - elibrary-network

volumes:
  mysql_data:

networks:
  elibrary-network:
    driver: bridge